[*]
wallpaper_mode=crop
wallpaper_common=1
wallpaper=/usr/share/rpd-wallpaper/license.txt
desktop_bg=#241f31
desktop_fg=#e8e8e8
desktop_shadow=#241f31
desktop_font=Nunito Sans Light 12
folder=/home/vthierry/Desktop
show_wm_menu=0
sort=mtime;ascending;
show_documents=0
show_home=0
show_trash=0
show_mounts=0

[zip.zip]
x=2
y=238

